name = "news-ja-batch"
main = "index.ts"
compatibility_date = "2024-04-16"

[observability]
enabled = true

[ai]
binding = "AI"

[[kv_namespaces]]
binding = "NEWS_TRANSLATIONS"
id = "5153c3cb172e445bb293d258ad1d4a0f"

[[queues.producers]]
binding = "NEWS_QUEUE"
queue = "news-ja-summarizer"

[[queues.consumers]]
queue = "news-ja-summarizer"
max_batch_size = 1
max_batch_timeout = 1

[triggers]
crons = ["0 6 * * *", "0 12 * * *"]
